services:
  vitis:
    image: xilinx-vitis-v2025.2:latest
    network_mode: host
    ipc: host
    privileged: true
    volumes:
      # GUI pass-through
      - /home/${USER}/.Xauthority:/home/${USER}/.Xauthority:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # device pass-through
      - /dev:/dev
      # mount work dir
      - .:/home/${USER}/work:rw
    working_dir: /home/${USER}/work
    environment:
      - DISPLAY=$DISPLAY
      - XDG_RUNTIME_DIR=/tmp/.X11-unix
    restart: no